### ISSUE TITLE
Possible solution for cross-platform

### ISSUE THREAD

**Issue by All0c** [133spider/AQLite#1]
Have you considered embedding the client inside [electron](https://electronjs.org/)? In my opinion it would be better doing it this way rather than having to load a web browser everytime for linux/mac users.

**Comment by 133spider** [comment]
Thanks for bringing it to my attention
Going to do some research into this and see if I can make something work from it

**Comment by 133spider** [comment]
Here's a image preview of me testing out AQLite in electron as a way to show my appreciation:
(Though, it's far from finished)
![](https://i.imgur.com/ixXzShn.png)

**Comment by henzosabiq** [comment]
As an alternative to electron, is it possible to create a standalone HTML file that runs this? I want to use it in Vivaldi (because it has tabs tiling feature) on Linux. I tried running the one at docs/index.html on Vivaldi and Chrome but it just won't run.

On vivaldi (despite what it said, I already enable Flash on this session) :
![screenshot_20190117_213803](https://user-images.githubusercontent.com/26890032/51325738-2e933680-1aa0-11e9-88e9-9976a8c2353b.png)

On chrome:
![screenshot_20190117_213853](https://user-images.githubusercontent.com/26890032/51325788-4a96d800-1aa0-11e9-9618-51e4b991471f.png)

My machine ;
Kubuntu 18.04
Chrome 71.0.3578.98
Vivaldi 2.2.1388.37

**Comment by 133spider** [comment]
> As an alternative to electron, is it possible to create a standalone HTML file that runs this? I want to use it in Vivaldi (because it has tabs tiling feature) on Linux. I tried running the one at docs/index.html on Vivaldi and Chrome but it just won't run.
>

The files under docs are outdated and were just used for testing purposes.
What you can do is to download **AQLite - SWF.zip** and open it by accessing it through your browser (So your URL should be... *file:///home/henzo/Games/AQLite/aqlite.swf*)
After opening it, it should be stuck at 0%. This is normal. Right click the client and open "global settings"
From there, go to the advanced tab and choose "Trusted Location Settings..."
![](http://shelterproject.naiaonline.org/assets/FusionCharts_Website/Tools/FlashPlayerSecuritySetup/Images/FlashPlayer3.jpg)
Inside there, add the .swf file that you extracted from **AQLite - SWF.zip** (So you would go to */home/henzo/Games/AQLite/aqlite.swf*)
After that, close out of everything and access the swf file using your browser again (So your URL should be... *file:///home/henzo/Games/AQLite/aqlite.swf*) and it should now work.

**Comment by henzosabiq** [comment]
Thanks for responding. Unfortunately, I still can't get any working flash player setting manager here (tried bunch of wonky packages, nothing works). I'll be using Electron version instead. 

Edit : Electron version not working. I will open a new issue.

**Comment by 133spider** [comment]
Electron hasn't been released yet as I'm still undergoing tests for it. 
Have you tried going to this link below as an alternative way to add the swf as a trusted location? (See steps #4-6 in the README.md under the tutorial for MAC users)
https://www.macromedia.com/support/documentation/en/flashplayer/help/settings_manager04.html

**Comment by henzosabiq** [comment]
Yes, it works fine now for both browser and desktop launcher from here : https://labs.adobe.com/downloads/flashplayer.html

**Comment by 133spider** [comment]
Thank you for showing me this
Much appreciated!

**Comment by All0c** [comment]
> Here's a image preview of me testing out AQLite in electron as a way to show my appreciation:
> (Though, it's far from finished)
> ![](https://camo.githubusercontent.com/b34b3d87d998d9d5e147d776086a1b74a432c99d/68747470733a2f2f692e696d6775722e636f6d2f6978587a53686e2e706e67)

It's looking good so far, good job!
