### ISSUE TITLE
Add labels displaying current and latest client version

### ISSUE THREAD

**Issue by henzosabiq** [133spider/AQLite#10]
First of all, I know people could just check the repo releases, but if they didn't, there's no way they could find out they're missing an update. I updated to 8.1 few days after its published exactly because of that reason. Aside from that, the new release is great, especially the no monster animation, thank you :)

**Comment by 133spider** [comment]
Thanks for suggesting this. I intended to put version labels on the ElectronJS launcher, but found myself limited. It never crossed my mind to put a version label inside the client that tells you if you're using an outdated version. Expect to see one in the next version -- thanks again!

**Comment by 133spider** [comment]
See version 9.0 in releases for fulfilled request
