### ISSUE TITLE
missing a file "ffmpeg.dll" so i cant open the program

### ISSUE THREAD

**Issue by vendoluxer** [133spider/AQLite#12]
so I would love for you to fix it somehow. I don't know a lot about programming but hopefully you can fix it. thank you in advance

**Comment by 133spider** [comment]
Perhaps your download got corrupted (or somehow didn't fully complete)
Try downloading again and make sure that the dll file is there
![image](https://user-images.githubusercontent.com/11169157/58386870-d07cdf80-7fba-11e9-8874-99b23098b68c.png)

**Comment by vendoluxer** [comment]
Thank you it worked😄
