### ISSUE TITLE
AQLite does not load (stuck at 0%) when routed through Tor

### ISSUE THREAD

**Issue by ghost** [133spider/AQLite#13]
So I use Qubes OS. And I route everything I do through Tor (Whonix Gateway). I have tried launching the default chromium based version and it gets stuck at 0%. I have also tried the Flash version by opening the .swf in Firefox. But it gets stuck at 0% aswell. When I'm not routing through Tor it works.

Anything you can do to fix it?

**Comment by ghost** [comment]
I routed the traffic through my firewall once it fully loaded then switched back to Tor before I logged in. And I don't know what your client is doing that is preventing me from loading at the start. But logging in with Tor is working completely fine.

**Comment by 133spider** [comment]
This is a very odd case. Usually, if it's stuck at 0% then that means you haven't added the program as a "trust" in Adobe Flash's control panel. 
Maybe this will help? Here's a list of the only connections AQLite makes:

- https://game.aq.com/game/
- https://game.aq.com/game/cf-userlogin.asp
- https://api.github.com/repos/133spider/AQLite/releases/latest
- https://game.aq.com/crossdomain.xml
- http://aqworldscdn.aq.com/game/gamefiles/

**Comment by ghost** [comment]
Okay well I have followed the exact instructions on how to set this up. I for sure have added the location to the trust list because without the Tor routing I am able to load. Seems like something is blocking whatever it's now blocking.

You think there is a way for you to remove the loading screen all together so that I start at the login screen?

**Comment by ghost** [comment]
There is something really weird going on here. This time, after trying a few times it worked. I got past the loading screen with traffic routed through Tor. 

It might just be good luck. Or, what I actually did that hopefully fixed it. Was going to the official https://aq.com website and clicked play and as I use NoScript I TRUSTED the ajax.googleapis.com and aq.com domain to be able to load.
After trusting it once, I put it back to DEFAULT on NoScript and went back to AQLite inside Firefox. After that it just works everytime. How many times I reopen Firefox. Shutdown the Virtual Machine that is running Firefox. And reloading Tor. 

Might just be luck. Hopefully it works or I'll be back.

**Comment by ghost** [comment]
Solved. I think. Well after not doing too much I believe I found the cause. The stuck at 0% might be because;

1. Google Captcha (Probably what is causing this)
2. You have to make contact with https://aq.com. (Which doesn't make sense)

Because Tor is a big and used network it's not surprising to see Google Captcha in all of the places. Anyways, that's probably why everybody else has the "stuck at 0%" issue, if they make too many Google requests they might see that IP address as a spammer/bot. And make you do a Captcha but because AQLite doesn't show that it's needed people can't get anywhere. Unless they go to https://aq.com and complete the Captcha. Or a VPN that is used by thousands everyday has the same problem.

@133spider I suggest you do NOT implement Google Captcha into the client, privacy reasons. Instead you should: if player is stuck in 0% for more than 30 seconds a popup will explain why and how to fix it. (Which is going to https://aq.com and completing Google's Captcha). Once that is done they can load the game.

Hopefully this is the correct solution. You can close this issue now if you want.

**Comment by 133spider** [comment]
Glad you figured out the solution!    
Rest assured, there is no Google Captcha built within the client at all. The client requires connection from AQW's official website to get the latest game files in order to run the game. So, all this Google Captcha thing is something I have no control over.
