### ISSUE TITLE
[Feature] Sort items by rarity

### ISSUE THREAD

**Issue by ghost** [133spider/AQLite#14]
So if this is possible to make. A new feature that could come in handy is to sort items by rarity.

For example: You wanna see all of the rares you have in your bank. Instead of scrolling through the entire bank to see what rares you have. Which, let's be honest is quite a hassle. You should be able to sort through Rare Rarity, Awesome Rarity, Seasonal Item Rarity and Legendary Item Rarity.. etc.

Believe this should be a nice overall new feature that many people will appreciate when looking for certain items, based on rarity.

**Comment by 133spider** [comment]
Noted! I won't release it separately on its own, but when I make a QoL update on the bank interface.
