### ISSUE TITLE
Rank 10 passive not showing on class overview

### ISSUE THREAD

**Issue by EzioMy** [133spider/AQLite#15]
Rank 10 passive isn't showing up in v11
![Sem título](https://user-images.githubusercontent.com/54557765/63725627-4cdcc400-c831-11e9-8bdd-b776f8aeb7e8.png)

**Comment by 133spider** [comment]
Thanks for the heads up. Rank 10 passives was accidentally disabled in v11 and I'll make sure to re-enable it in the next version.
