### ISSUE TITLE
Some Features that could be added.

### ISSUE THREAD

**Issue by Heromerom** [133spider/AQLite#16]
Heya! I was thinking about an feature to AQLite and I got some ideas that came from other games and it will improve our gaming experience.

1. Mouse Button
2. Inspect User
3. Chat Tabs

By the way, I don't know if those things are possible to make, but here is my suggestion.

### **MOUSE BUTTON**
**On Chat Box:**
Actually, we can whisper other players by pressing **SHIFT** + **LEFT CLICK**. But what if we could Party Invite, Guild Invite or any other action throught a simple combination of keys?

For example:
**SHIFT** + **A** + **LEFT CLICK** = Invite to Party
**SHIFT** + **D** + **LEFT CLICK** = Duel Player
**SHIFT** + **F** + **LEFT CLICK** = Friend Invite
**SHIFT** + **G** + **LEFT CLICK** = Guild Invite
**SHIFT** + **R** + **LEFT CLICK** = Report Player

**On Players:**
Imagine that we could open this menu by **pressing the Right Button over any character** in game instead clicking them and then _Options_.
![image](https://user-images.githubusercontent.com/49551386/64130451-bb250780-cd98-11e9-9eff-9f0cb2fcd215.png)

### **INSPECT USER**
This is an addition to the **Menu** I've mentioned before. We could **INSPECT** any player throught that interface.

**It could show:**
- Armor;
- Weapon;
- Helm;
- Cape;
- Pet;
- and its enhancement, if possible :)

And, if we click on any item, we'll be redirected to the Wiki.
`http://aqwwiki.wikidot.com/{item name}`

An adittion to **On Chat Box** actions:
**SHIFT** + **C** + **Right Click** = Inspect User

### **CHAT TABS**
It's just something visual to sort messages on the Chat Box by groups. Instead typing /[_**p**_,_**w**_,_**g**_ or _**s**_], we could just click on the tab we want to chat.

![image](https://user-images.githubusercontent.com/49551386/64130834-4901f200-cd9b-11e9-80f7-9a82fd206f7d.png)

**Comment by 133spider** [comment]
These are all great ideas!

- The keybinds (Shift + Key + Left Click) will be implemented when I create a keybind customization interface

- I can envision Inspect Users having a draggable UI in-game as if you're viewing someone's character page

- Chat tabs are going to be a little tricky to design. Need to make them fit in with the game's UI

Overall, these are something I'm definitely going to be implementing and hopefully in the next version. Thanks for these!

**Comment by Heromerom** [comment]
Thanks for your attention, Spider! By the way is there any way to make a client that can run at mobile (Android, ofc)?

**Comment by 133spider** [comment]
A little update:

- Keybinds will be in a later update. Still planning out the Keybind Settings UI.
- I've looked into it, and unfortunately, retrieving user equipment by their name is not possible.
- I have something else planned in mind for Chat, but I'm going to need some time to work it out.
