### ISSUE TITLE
Add-ons remain on screen after logout

### ISSUE THREAD

**Issue by Heromerom** [133spider/AQLite#17]
If we got Disconnected or Log Out while those Interfaces are open, they won't diseaper until I login again or close it.

**Quest Item Preview**
![Quest Item Preview](https://user-images.githubusercontent.com/49551386/64481623-18182780-d1b6-11e9-8362-1b0b60cc024e.png)

**Custom UI Drop 1**
![Custom UI Drop 1](https://user-images.githubusercontent.com/49551386/64481627-236b5300-d1b6-11e9-9660-720adf1da8c9.png)

**Custom UI Drop 2**
![Custom UI Drop 2](https://user-images.githubusercontent.com/49551386/64481673-68dc5000-d1b7-11e9-84c6-1ad8ae665f15.png)

**Inventory Search Box**
This one only happen thought Disconnection, since we can't logout with the inventory open.
![Inventory Search Box](https://user-images.githubusercontent.com/49551386/64481632-439b1200-d1b6-11e9-8198-25286508020c.png)

**Comment by 133spider** [comment]
Noted -- thanks.
