### ISSUE TITLE
Update Quest Progress

### ISSUE THREAD

**Issue by gubrus50** [133spider/AQLite#18]
## Issue
When you accept the quest, complete it but haven't turned it in,
and if you try to collect more of the required items from the quest.
Then those collected items will not be updated at the quest log.

## Preview
<video width="320" height="240" controls>
  <source src="https://video.wixstatic.com/video/3a41ca_6a37bb1afd94415ead4ded94cd1a0e42/480p/mp4/file.mp4" type="video/mp4">
 Your browser does not support the video tag.<br/>
You can also check the preview video on wix.com:
<a href="https://video.wixstatic.com/video/3a41ca_6a37bb1afd94415ead4ded94cd1a0e42/480p/mp4/file.mp4" target="_blank">https://video.wixstatic.com/video/3a41ca_6a37bb1afd94415ead4ded94cd1a0e42/480p/mp4/file.mp4</a>
</video>

**Comment by 133spider** [comment]
Haven't overlooked this one. Will get around to it, but there's something I want to do with the Quest Progress UI and this will be included into it.
