### ISSUE TITLE
Class Actives/Auras UI

### ISSUE THREAD

**Issue by Letisss** [133spider/AQLite#20]
Please have skills/passives icons when the enemy using buff or debuff . I can only see the normal passive icon.
![skillicon2](https://user-images.githubusercontent.com/57785984/68919166-9b03c280-07a3-11ea-9988-2d71e5b7d12d.png)

**Comment by Letisss** [comment]
lol
![image](https://user-images.githubusercontent.com/57785984/68919367-5fb5c380-07a4-11ea-979f-a6270b93d973.png)

**Comment by Letisss** [comment]
![image](https://user-images.githubusercontent.com/57785984/68993815-aa236700-08ae-11ea-9711-187772aa7a7d.png)
buff/debuff bug again

**Comment by zZeroCode** [comment]
Currently using the latest version of AQLite (v.13). I have the Class Actives/Auras UI option on but it's not showing on the UI.

![noUIaurav13](https://user-images.githubusercontent.com/49535427/70012268-3eaaec00-1574-11ea-876d-67b484d21d7d.png)

![noUIv13](https://user-images.githubusercontent.com/49535427/70012129-c8a68500-1573-11ea-9c7a-4e8abe2cbcc8.png)

**Comment by 133spider** [comment]
Issue has already been fixed with the buff/debuffs displaying for the wrong player target
As for proper skill icons instead of "gears", there is no way (at the moment) for me to obtain proper skill icon data from other players' classes. If I find a way, then I am definitely going to add it.
