### ISSUE TITLE
Class Actives/Aura UI v.13

### ISSUE THREAD

**Issue by zZeroCode** [133spider/AQLite#22]
Currently using the latest version of AQLite (v.13). I have the Class Actives/Auras UI option on but it's not showing on the UI.

![noUIaurav13](https://user-images.githubusercontent.com/49535427/70012472-c1cc4200-1574-11ea-98f3-7c0353891d26.png)

![noUIv13](https://user-images.githubusercontent.com/49535427/70012480-c5f85f80-1574-11ea-9009-294a576a0df3.png)

**Comment by 133spider** [comment]
Thanks for the heads up!
v13.1 has been released to fix this issue
