### ISSUE TITLE
Application error

### ISSUE THREAD

**Issue by zhamen** [133spider/AQLite#24]
I am playing on AQLite and after 5 minutes I am getting crashed and 2 windows are opening:
"Adobe flash player ... stopped working. A problem caused the program to stop working correctly. Windows will close the program and notify you if a solution is available."
"AQLite v.13.1.exe - Application Error
The instruction at 0x ... referenced memory at 0x ... .The memory could not be written.
click OK to terminate the program"

**Comment by 133spider** [comment]
Not sure exactly what's causing it for you. 
It sounds like:

1.  Your RAM is corrupted (you need to perform a memory test)
2.  Applications running in the background could be causing this issue (by them taking up RAM)
3.  You're out of RAM (though this is unlikely)

How much RAM do you have? How often does this happen?

**Comment by ghost** [comment]
it happened when i shut down the pc. i resolved that by uninstalling the "AQLite v13.1.exe" and unzipping it from "Windows.-.AQLite.v13.1.zip"(i have it on desktop), it takes 5 seconds so it's not a problem anymore
