### ISSUE TITLE
My elmedia is playing Aqlite but in reverse

### ISSUE THREAD

**Issue by random-arch** [133spider/AQLite#25]
I don't know what happened here [https://gyazo.com/335cfaaf7da50836d7d2991a463e07d8](url)
but everything on my player is on reverse and upside down can you help me with this?

**Comment by 133spider** [comment]
![image](https://user-images.githubusercontent.com/11169157/70757134-5c561f00-1cf3-11ea-8eb8-fbda4e9cbb78.png)
