### ISSUE TITLE
Feature Request - Map Hopping

### ISSUE THREAD

**Issue by Marexn** [133spider/AQLite#27]
Hi, i came up with an idea that would be neat to see added.

Have Button for a menu, where you are able to create instant "/join" commands teleport for different maps.

Way it would work

• Button to open drop down menu, than can be added through AQLite Settings,
• The feature has bar where you can write name of a place,
• When pressed enter or an checkmark etc; it creates button of the word you put into the bar,
• When pressed onto of the newly created button, it pastes the word onto the chat and automatically enters it.

How to prevent people from spamming with it

When pressed on the bar to be able to write
• You only have to write the location,
• The "/join" command is bound to be first word of the sentence,
• When the button has been pressed it activates an 2 second cooldown.

This would be more of an convenience option.
I’ve noticed that a lot of the times from talking with friends that the main reason they hate grinding something like pet quests is because they just cannot bother copy + pasting the different “/join” commands over and over again, and to have them to go on Notepad or different tab of wiki where they’ve highlighted the places name already to then copy it, and of course it could be used for stuff like Yulgar hopping or going through your favorite places.

Thanks for hearing me out, keep it up.

**Comment by gubrus50** [comment]
What about this. Create an option where you can save your locations.

You have an input where you paste your **location_name** and a plus button to add your location to the **storage**. Once you've added some locations to the list. You go to the 'AQLite' settings and press button **"My Locations"**. A popup will appear with ordered locations with an additional search bar. Once you double-click on one of the locations, the popup closes and the full command "/join my_location" gets inserted to the chat. 

There is no need for "spam-prevention" as the time taken for getting to **My Locations** option seems to be just enough.

**Comment by Marexn** [comment]
I think that's pretty good idea. I think there could also be like an "Faivorite" system with the different locations. So when you open the tab with all of the different locations, you could add like an Star "⭐" or Heart "❤️" icon to them, which would put them ontop of the list. I think you could have like Max 3 or 4 at time faivorited. Also the tab/popup could have it's own additional button along with the Quests and Custom Drop UI, to have the Locations button circle around the player Icon.

Also, as side note off the original feature subject. I think the Custom UI Drops are amazing, but i think it'd be nice to have couple more features for it, such an button to instantly add an item that's been dropped into the Black List. Additionally, having White List and Sell button on the UI's would be a very convenient feature.

![Request](https://user-images.githubusercontent.com/9413484/72682553-f53c3f00-3ad6-11ea-8df2-847846178a84.png)

**Comment by 133spider** [comment]
- [X] Travel Menu
- [ ] Selling an item from a drop

Selling an item from a drop is not possible because the server has been coded to only recognize items that are *inside* in your inventory

I could make it so the item would be added into your inventory, and then sell the item; however, the server itself **can** create invisible items that occupy your inventory space, and the fact that some people just won't realize that they need free inventory spaces. There's too many down-pouring factors that this solution won't be any efficient.

I appreciate your ideas!
