### ISSUE TITLE
Fix hide players please :)

### ISSUE THREAD

**Issue by ghost** [133spider/AQLite#3]
When activating hide players it still shows names and on some rare occasions still shows some pets. When i activate hide players i would love for them to be completely gone! Thanks!

**Comment by 133spider** [comment]
You can hide pets by enabling "Hide Other Pets" under the gameplay tab that's already in AQW's own client
As for the name, I've added that as so monsters don't teleport out of the map trying to find the player that no longer exists on your screen.
However, I'd be glad to bring it back so expect it for the next update

**Comment by 133spider** [comment]
See version 5.0 in releases for fulfilled request
