### ISSUE TITLE
*Bug* - Client might close by itself

### ISSUE THREAD

**Issue by Marexn** [133spider/AQLite#30]
Hi there.
I've been using the client regularly for sometime right now. I have just re-installed Windows, and there is this bug that occurs occasionally, where the client would just close itself. This is actually happening right now, as i'm writing this.

Here's how it occurs,
- Open the client
- Log into my account
- Go to "Artix" server
- Do "/join party"
- Go to my usual spot, and AFK.

Couple minutes later, the client closes itself.
This used to be bigger problem with my Alt account, which i use to farm from time to time with, and i thought that might've been just the games flaws due to how many drops i might've gotten.

The client does not crash, there are no messages, it just closes.
I do not know the cause of it, if there's something wrong on AQW's side, of the clients side. Could it be one of the plugins?

I'm running couple of tests as i'm writing this to see what triggers the client to close.
I had opened the client twice, and had my account logged in one of the clients, and the other client i hadn't logged onto. I did the same process as mentioned up top, and the client which had my account running, closed.
I ran my account on Yulgar for little bit, and i think there might be an action from skill...? Maybe... That causes it... I can't verify that for 100%, or if it's some kind of an command that's been set into the client itself to fuck with people (which would be a really funny troll tbh of you).

Regardless, i don't know whats the exact cause for the client closeing itself, but i hope that this can give some kind of an idea on what might be the cause of it, or how to go on about to finding the cause. I will also inclued some of screenshots from the client settings i've got enabled. (No Black-Listed items in use).
![kuva](https://user-images.githubusercontent.com/9413484/73748793-da1e3000-4762-11ea-96a7-fd228c64f5da.png)
![kuva](https://user-images.githubusercontent.com/9413484/73748853-f4f0a480-4762-11ea-80c4-5d0451b666f1.png)
![kuva](https://user-images.githubusercontent.com/9413484/73748892-0174fd00-4763-11ea-8837-221507608d07.png)
![kuva](https://user-images.githubusercontent.com/9413484/73748921-0cc82880-4763-11ea-99ce-11a170b94e69.png)
![kuva](https://user-images.githubusercontent.com/9413484/73748943-16519080-4763-11ea-8625-8d3d3b5e6b5f.png)
![kuva](https://user-images.githubusercontent.com/9413484/73748999-2b2e2400-4763-11ea-8c72-ce61bbe302bf.png)

**Comment by 133spider** [comment]
Thank you for the report!
Unfortunately, this is an issue with Flash Player 10's horrible and outdated memory management. Due to that, the memory threshold in AQLite exceeds the maximum and crashes without warning.

To resolve this, I've officially retired the Flash Player version and have brought back ElectronJS with Wide-Screen support. You can get it at: https://github.com/133spider/AQLite/releases/latest/

Sorry for the inconvenience I've caused you!

**Comment by Marexn** [comment]
> 
> 
> Thank you for the report!
> Unfortunately, this is an issue with Flash Player 10's horrible and outdated memory management. Due to that, the memory threshold in AQLite exceeds the maximum and crashes without warning.
> 
> To resolve this, I've officially retired the Flash Player version and have brought back ElectronJS with Wide-Screen support. You can get it at: https://github.com/133spider/AQLite/releases/latest/
> 
> Sorry for the inconvenience I've caused you!

Glad to hear that you're already aware of this. And don't worry, it hasn't caused me too many inconvenient situation so far, just little hickups if you will. With this responce, i will close the issue.
Appreciate the quick response.
