### ISSUE TITLE
Can't run AQLite

### ISSUE THREAD

**Issue by silvermamba1324** [133spider/AQLite#31]
Tried to run the AQLite.swf program but it's stuck at 0%. Made sure it didn't have accents in the title and added AQLite file to the Flash Player list.

**Comment by 133spider** [comment]
You're not supposed to run the swf file unless you added it to your trusted path location in Adobe Flash's global settings panel.
It sounds like you put a typo or the wrong location when you added AQLite to the global settings panel?
Download the actual client here where it says "CLICK ME FOR LAUNCHER DOWNLOAD OPTIONS": https://github.com/133spider/AQLite/releases/latest/

**Comment by 133spider** [comment]
Assuming fixed,
