### ISSUE TITLE
Error when launching

### ISSUE THREAD

**Issue by Yehab** [133spider/AQLite#33]
Whenever I try and launch the application I get the error "A javascript error occurred in the main process" its an uncaught exception saying it failed to get a pepperflashsystemplugin

**Comment by 133spider** [comment]
https://get.adobe.com/flashplayer/otherversions/
![image](https://user-images.githubusercontent.com/11169157/74007053-400ce200-4932-11ea-9138-9cec8978c8a1.png)

**Comment by 133spider** [comment]
v2 of the ElectronJS launcher in which you don't need to install PPAPI from Adobe has been released
Check out release v13.2
