### ISSUE TITLE
Warning Box Stuck

### ISSUE THREAD

**Issue by zZeroCode** [133spider/AQLite#34]
I'm using the latest version of AQLite (13.3).

![image](https://user-images.githubusercontent.com/49535427/74334864-12dd8b00-4d9b-11ea-84db-4bafce3ca4ed.png)

The warning box is stuck after clicking Yes/No. Even after relogging or changing servers. Occured when shift-clicking a drop with SBP's Custom Drop UI. Not confirmed if it's also the same case as Custom Drops UI.

Edit: Warning box remains stuck while joining other rooms.

![image](https://user-images.githubusercontent.com/49535427/74334919-3accee80-4d9b-11ea-853a-8a4bfef45174.png)

![image](https://user-images.githubusercontent.com/49535427/74334949-4ddfbe80-4d9b-11ea-8f0b-7b41da9fd335.png)

**Comment by 133spider** [comment]
Hmm, I'm not able to recreate this
Did you perhaps shift+click'd multiple times?

**Comment by zZeroCode** [comment]
I remember shift-clicking items twice but there were times where I have only shift-click’d once.

Perhaps this bug occurs randomly?

**Comment by 133spider** [comment]
I'll keep this issue open.
If you ever get the chance to figure out what is exactly is causing it then that would be much appreciated!

**Comment by zZeroCode** [comment]
Good news, I've recreated it! Whenever I accept and complete a quest (with 'Reaccept quest after turn-in' option on) there is always a delay on accepting the item drop the second time I accept and complete the same quest (I've always seen this one happen all the time). 

I believe this specifically only a functionality flaw on SBP's Custom Drops UI and apperently if you shift+click the item you want to blocklist during that "delay", it will be stuck there.

Edit: Shift+clicking multiple times does not recreate the bug. It has to be during the "delay" specifically

Here is the bug in action again.
![image](https://user-images.githubusercontent.com/49535427/74529361-abeddc80-4f28-11ea-8d84-8c12d8e55f92.png)

![image](https://user-images.githubusercontent.com/49535427/74528835-8e207780-4f28-11ea-9a6d-4e7e4134d4c4.png)

![image](https://user-images.githubusercontent.com/49535427/74528977-95e01c00-4f28-11ea-92ab-7365067dea58.png)

It's very hard to explain as showing you would be the only way I can prove this bug but I'll try to record it in action. I hope you understand my explaination!

Edit: I am still using the same version of AQLite, just without the Ninja Hotfixes.

**Comment by 133spider** [comment]
Trying to recreate it and shift+click as fast as possible to do it during the 'delay', but I've been unsuccessful so far. 

But just for clarification, when you click "Yes", it gets stuck on the screen correct? If this is true, then I think I know where to look.

**Comment by zZeroCode** [comment]
Yes, It only happens when I click ’Yes’.

**Comment by gubrus50** [comment]
It is true. Yesterday when I was farming I've been banning many of the items, and then this issue appeared I think when I shift+clicked the "+"/yes button in "SBP's Custom Drops UI". So this issue is real.

**Comment by 133spider** [comment]
Issue has been fixed. See the new v13.5
The only downside is that if you were to remove an item from the blacklist, you must relog
From my testings, relogging is absolutely necessary, otherwise the game will refuse to give you the item drop (even if you've removed the item from the blacklist)
