### ISSUE TITLE
Features split-up

### ISSUE THREAD

**Issue by henzosabiq** [133spider/AQLite#38]
We love what you're doing with AQLite spider, but wit with each version coming the client is becoming more and more laggy to play with. I have like 5-6 version somewhere on my disk, trying to find one bearable enough to play and feature-wise good enough for farming. I assume this has to do with flash limitation since I'm guessing you've optimized it as good as possible. 

I suggest to split upcoming AQLite version into 3 category; complete (all features in), combat (keep minimum crucial feature for farming), and casual (mainly for hangout or afk at yulgar; put in cosmetics-related features should be prioritized here). What do you think?

**Comment by 133spider** [comment]
The idea sounds intriguing, but a large majority of the people just end up using the one with all the features.
I can assure you that I'm always trying to experiment new ways to better the performance in every update (in fact: version 13.0 was released as a complete optimization overhaul to try and combat performance issues). Truthfully, continuing my search for better performance in Flash slowly makes me understand AE's choice to abandon their Flash games, but I'm not one to give up.

However, if you have an outdated/old processor then it's unfortunately out of my hands.

**Comment by henzosabiq** [comment]
I see, thanks for explaining. Closing this issue now.
