### ISSUE TITLE
how do I fix this error in AQLite

### ISSUE THREAD

**Issue by sus13** [133spider/AQLite#39]
I have been trying for a long time now and I tried to uninstall and install again and I'm still having this error does anyone knows how to fix please, thanks.
<img width="417" alt="error" src="https://user-images.githubusercontent.com/62361623/77016629-49ee2000-6989-11ea-8303-544ac27bcb48.PNG">

**Comment by 133spider** [comment]
Have you tried running the exe as admin?
From the looks of it, something on your computer is  disallowing needed operations/changes for AQLite to run.

**Comment by sus13** [comment]
> Have you tried running the exe as admin?
> From the looks of it, something on your computer is disallowing needed operations/changes for AQLite to run.

yes i have and still didnt work

**Comment by 133spider** [comment]
![image](https://user-images.githubusercontent.com/11169157/77023199-dfb58b00-6948-11ea-9869-7410f3476fa8.png)
Found this from a stackoverflow post
Checked on my own system and Ransomware is disabled on my PC. Perhaps it got enabled on yours?

**Comment by sus13** [comment]
> ![image](https://user-images.githubusercontent.com/11169157/77023199-dfb58b00-6948-11ea-9869-7410f3476fa8.png)
> Found this from a stackoverflow post
> Checked on my own system and Ransomware is disabled on my PC. Perhaps it got enabled on yours?

I had to delete my virus protection because I couldn't have access to this settings and now it worked thanks!
