### ISSUE TITLE
Reaccept Quest not working?

### ISSUE THREAD

**Issue by SynTheLegend** [133spider/AQLite#41]
Tried in both 13.4 and 13.5, with different quests, and the Reaccept Quest feature is not working.

**Comment by SynTheLegend** [comment]
Actually, it might just be Crag and Bamboozle causing the problem.

**Comment by PedroHaoTavares** [comment]
I'm experiencing this same problem, but I only tested it on Crag and Bamboozle.

**Comment by pmiggs** [comment]
I tried it on other quests and it still reaccepts them. The problem is exclusive for Crag and Bamboozle quests. It might be due to the new temporary updates on the pet that is giving the problem, i.e. the extra "Blood Gem of Nulgath" reward on Supplies to Spin the Wheel and/or the boosted drop rates of all the gems.

**Comment by PedroHaoTavares** [comment]
True, this is what I'm imagining. Because in other quests it's working normally.

**Comment by SynTheLegend** [comment]
It was also affecting Drudgen, but has been fixed now.

**Comment by SynTheLegend** [comment]
Once again, not working. I checked Crag (Supplies, Bamboozle v Drudgen), Drudgen (Supplies), Black Knight Orb quest, Void Highlord's Challenge.
I believe, based on pure conjecture, that this issue is somehow connected to the 72hr Nulgath gems boost, because for a while after the implementation and again now, the drop rates on quest items display as a X.XX% rather than just X%, and the problem has only occurred while the percent display was altered (which happened after the changes to gem drop rates)
![image](https://user-images.githubusercontent.com/62631251/77859159-61b97580-71cd-11ea-80e6-10d7407e04dc.png)

**Comment by 133spider** [comment]
Thanks for the awareness! v13.6 has been released to squash this issue.
