### ISSUE TITLE
main.as file missing?

### ISSUE THREAD

**Issue by 1mi0** [133spider/AQLite#44]
On purpose or just forgot to upload it?

**Comment by 133spider** [comment]
AQLite is largely influenced by OSRS's RuneLite. With that being said, RuneLite had an agreement with the official game developers(Jagex) that they would hide/take down the code in their RuneLite github that shows how they inject themselves into the game. Likewise, I followed their steps and hid main.as from being easily accessible/readable.

**Comment by 1mi0** [comment]
Well, then you should know that the previous versions still have it.

**Comment by 133spider** [comment]
Thanks for telling me, but it's fine since there are other means of getting to the main.as. Just preventing it from being easily accessible/readable from this github repo's front page is good enough.
