### ISSUE TITLE
Few bugs and suggestions

### ISSUE THREAD

**Issue by WooXZerah** [133spider/AQLite#5]
I have been using AQLite since it's release and now I'm ready to report some bugs and make suggestions for the improvement of this amazing tool. The bug list below are not in any particular order.

### Bugs

[**Screenshot**](https://imgur.com/WSLdcT4)
**1.** I've noticed that few items while droped using Custom Drops UI shows the wrong quantity. This bug may affect other items but I will list only those I know for sure that shows the wrong quantity.
**Items affected**: Dark Spirit Orb, Shadow Shield, Shurpu Blaze Token and Glacera Ice Token.
And I think that is worth to mention this, most of the items listed above are from daily quests to get classes.

[**Screenshot**](https://imgur.com/cQn0nSZ)
**2.** I don't really know if this is a bug or if it's supposed to be this way but the quests drop rate only shows for the quests that has **"Recieve at random"**, quests with **"you will recieve one of the following items"** doesn't has the drop rates on it. If it's supposed to be like this, take this as a suggestion and add drop rates for this kind of quests if it is possible to do so.

[**Screenshot 1**](https://imgur.com/bCoE8La) [**Screenshot 2**](https://imgur.com/iE2CpYq)
**3.** When there are several items on the Custom Drops UI list and you turn it back to normal, the items then will be shown with the normal drop system, but if you just logged in and droped few items and turn on the UI Drop system so you can choose which items you want using the preview you just can't, the items won't show on the list.

[**Screenshot**](https://imgur.com/Dnv0LGq)
**4.** The quest log with turn-in should only appear when clicking quests **after** clicking the Icon, not straight away. This way we would be able to open the temp inventory to see which and how many temp items we have or even equip temp items.

### Suggestions

**1.** Since AE implemented the turn off animations functions, I think the option should be removed from AQLite but would be nice if the option **"show your skill animations only"** worked together with AE function when active.

**2.** When the Custom Drop UI list is closed it only appears again if a new item is droped, I think would be useful to bind a key to open the list or a button on options to open it again without needing to drop a new item.

[**Screenshot**](https://imgur.com/Ykn2be9)
**3.** When I first saw the Class passive UI, I thought it would work together with Active Auras and show when a passive is active but I doesn't seems to be working that way. Would this be possible to do? Show on active auras when a passive skill is active? If not I think beside showing the rank 10 passive the function is pretty much useless since the rank 4 and rank 5 passive can be found on stats/class panel, so I think this Passive UI should be removed and added an extra icon for rank 10 passive when a player opens the stats/class panel.

**I also wanted to thank you for creating this beatiful AQW Client and making it open source.**

**Comment by 133spider** [comment]
**Bugs**
1. Will be looking into this, thanks for the info!
2. Not really a bug. Those types of rewards do not have a quest drop rate. Instead, they all have an equal chance of dropping. For example: 5 rewards will each have 20% drop rate, and 2 rewards will each have a 50% drop rate. If you own one of the rewards already, then you will automatically get the other reward.
3. Items are only displayed in the custom drops ui if and only if the item is dropped *while* custom drops ui is enabled. Unfortunately, it has to be this way.
4. Will do.

**Suggestions**
1. AE's version of turning off animations is making every other user in the room have a permanent idle stance so I think I'll just leave AQLite's option in.
2. Already on it for the next version!
3. Passives are always active on default except for rank 10 passives. Rank 10 passives do appear in Active Auras, they just have a random chance of triggering. I've been considering the idea for adding an extra icon for rank 10 passive in the stats/class panel. That I will do.

**Comment by 133spider** [comment]
See version 7.0 in releases for the bugs that have been fixed and suggestions implemented
