### ISSUE TITLE
Issues with gold acquisition?

### ISSUE THREAD

**Issue by Brian-Valdez** [133spider/AQLite#55]
After downloading and running AQLite, everything functioned properly until I realized my gold count wasn’t moving. After killing mobs or turning in quests it seems almost like I am not at all receiving any gold and it is currently stuck at 4000096 gold. Mobs only drop XP but no gold, I can purchase something and then receive gold but it stops at its current number. Is this a bug?

**Comment by gubrus50** [comment]
Unfortunately, this is not a bug, it has been done deliberately by the AQW developers themselves and I don't know the details behind that decision.

**Comment by Brian-Valdez** [comment]
So in order to farm gold I’d need to do it in the AE launcher?

**Comment by 133spider** [comment]
The game itself caps the maximum gold at 4 million. You can not gain anymore gold no matter what you do.

**Comment by Brian-Valdez** [comment]
Ahh I did not know that, thanks for letting me know
