### ISSUE TITLE
Quest automatically gets abandoned

### ISSUE THREAD

**Issue by zZeroCode** [133spider/AQLite#57]
Hi there,

I am currently running the latest version of AQLite on both Electron JS and Flash Projector.
![image](https://user-images.githubusercontent.com/49535427/84926451-b3d2ae80-b0cb-11ea-90e0-215dcd0d687a.png)

Whenever I press the 'L' key, the hotkey for the Quest Menu, my quest automatically get declined or abandoned. I discovered this bug when I was farming **Mine Crafting** quest in /necropolis. I have also tested this on other servers and with other quests but it seems like **Mine Crafting** quest is the only quest affected. I have tried recreating this on Artix Launcher and on browser and it doesn't seem to recreate it at all.

However, it seems like this affects both Electron JS and Flash Projector versions. Am I the only one that is having this problem?

**Comment by 133spider** [comment]
Fixed the issue with quests like "Mine Crafting" in version 15.1!
Thanks for your report
