### ISSUE TITLE
Bank showing no helms

### ISSUE THREAD

**Issue by Archeol** [133spider/AQLite#63]
I have no idea if other things are being reduced since I have so much stuff in the bank, but helms are showing as completely 0, and all filters are indeed off. I'm using the beta 15.2.

**Comment by Archeol** [comment]
well its working again today so idk

**Comment by 133spider** [comment]
When you're still in combat (according to the server and not the client) it will refuse to load your bank items no matter what. This is only fixed if you relog.

However, I will look into seeing if I can get the server to still send your bank data instead of being forced to relog.

**Comment by Archeol** [comment]
well it was only for helms in the bank location, but it doesn't seem to happen again so I guess it might've just been some kind of one-time weird glitch thing
