### ISSUE TITLE
AQLite

### ISSUE THREAD

**Issue by Mareczkoks** [133spider/AQLite#69]
Hello

Why the application wants to access the webcam?

**Comment by 133spider** [comment]
![image](https://user-images.githubusercontent.com/11169157/106378410-6c96e680-6359-11eb-848e-f4505a61cab3.png)
You're probably referring to something like this?
This webcam tab (which can be found by right-clicking Flash and choosing Settings) is global to all games/applications that use Flash Player. You can just ignore it.
