### ISSUE TITLE
Quest item drop rate no longer showing

### ISSUE THREAD

**Issue by henzosabiq** [133spider/AQLite#7]
I just realized this today. Is it patched by the devs? Can you make it work again?

**Comment by 133spider** [comment]
Hmm?
It seems to be working just fine. Try turning the feature off and then back on?
![image](https://user-images.githubusercontent.com/11169157/52977998-4520fc00-3384-11e9-9ccc-8a16f5dd570e.png)
Perhaps you can also tell me what quest you are trying to see the drop rates in?

**Comment by henzosabiq** [comment]
Its Gathering Unstable Essences from Braeus in Shadowfall. I did relog, re-enabled the feature, but its still not showing. 
![screenshot19-02-201914_59_43](https://user-images.githubusercontent.com/26890032/52999005-4111de80-3457-11e9-8662-7a94a8d001ee.jpg)

Edit : nevermind, I didn't notice it says "You will receive one of the following item" before. My bad.
