### ISSUE TITLE
AQ Lite Bugs

### ISSUE THREAD

**Issue by 133VHL** [133spider/AQLite#75]
I don't know if it's just me but there's a few things I had issues with. With quest and task, you can't really interact with it. For example, when given a puzzle, you can'y leave the instructions therefore I cannot start the task. Another flaw I faced was that when there's a quest option on the top right corner (when it shows the NPC) I can't click on it to see the quests. Other than that AQL has been treating me well. [
![Screenshot_2](https://user-images.githubusercontent.com/72644382/95648032-11c73f80-0a89-11eb-80be-67d93233d1d7.png)
![Screenshot_5](https://user-images.githubusercontent.com/72644382/95648060-5e127f80-0a89-11eb-8fcb-c8884451bc25.png)
![Screenshot_3](https://user-images.githubusercontent.com/72644382/95648062-5f43ac80-0a89-11eb-89f2-da5b46ebf27f.png)

**Comment by 133spider** [comment]
It's because you have "Disable Map Animations" toggled on

I've added a warning message about this whenever you toggle the feature on in the next version -- thanks.
