### ISSUE TITLE
Privacy questions regarding "Char Page"

### ISSUE THREAD

**Issue by burneracc69** [133spider/AQLite#8]
Hi, as a privacy advocate I have been wondering how you handle JavaScripts on the website whenever you click "Char Page". The latest version 7.1 has that feature and I don't like it at all. Now I don't understand programming that much. But any way you could make an option, ON/OFF, to open redirected links in the default browser instead of your web fetcher or whatever you do. Or simply block all JavaScripts other than AQ.com. Everything else is tracking scripts except Bootstrapcdn.

Thanks for this wonderful program, it really is convenient! You even made a Linux client before the actual team which still is in "experimental". Bruh... Lol. xd, Ooof. .... 
![unknown](https://user-images.githubusercontent.com/48022878/53423205-d6255200-39d8-11e9-9aaa-55a559c2712b.png)

**Comment by 133spider** [comment]
Hi there. Thanks for using AQLite!

To change AQLite to open links in your default browser instead, do the following:
1. Go to the directory AQLite/resources/app
2. Open the file "main.js" in a text editor
3. Remove everything and replace it with the code below
```
'use strict'

const { app } = require('electron')

var flashTrust = require('nw-flash-trust');

const Window = require('./Window')

const path = require('path')

const {shell} = require('electron');

// Specify flash path, supposing it is placed in the same directory with main.js.
let pluginName
switch (process.platform) {
  case 'win32':
    pluginName = 'pepflashplayer.dll'
    break
  case 'darwin':
    pluginName = 'PepperFlashPlayer.plugin'
    break
  case 'linux':
    pluginName = 'libpepflashplayer.so'
    break
}

app.commandLine.appendSwitch('ppapi-flash-path', path.join(__dirname, pluginName))

var appName = "aqlite"

var flashPath = path.join(app.getPath('userData'), 'Pepper Data', 'Shockwave Flash', 'WritableRoot');

var trustManager = flashTrust.initSync(appName, flashPath);

trustManager.add(path.resolve(__dirname, 'aqlite.swf'));
trustManager.add(path.resolve(__dirname, 'loader.swf'));

let mainWindow


function main() {
  let mainWindow = new Window({
    file:'index.html'
  })
  mainWindow.webContents.on('new-window', (event, url) => {
    // stop Electron from opening another BrowserWindow
    event.preventDefault()
    // open the url in the default system browser
    shell.openExternal(url)
  })
}

app.on('ready', main)

app.on('window-all-closed', function () {
  app.quit()
})
```

4. Save the file and start AQLite
That should be all!

**Comment by 133spider** [comment]
assuming issue solved
