### ISSUE TITLE
Re's Sporty Wear animation bug

### ISSUE THREAD

**Issue by Ashenine** [133spider/AQLite#81]
Apparently Re's Sporty Wear armor has an animation bug when moving around, and can end up bugging out when swapping armors afterwards

![ReSportyMovement](https://user-images.githubusercontent.com/77877444/105573531-62517700-5db2-11eb-9973-8d1a6287499b.jpg)
This is what shows when moving, and will change to /dance when stopping and swapping armors.
(This only happens on AQLite and not the actual game launched through the Artix Launcher)

**Comment by 133spider** [comment]
That's funny -- I've looked into this and it's because whoever made this armor left code for a mount armor on her robe

Fixed in the next version -- thanks.
