### ISSUE TITLE
Inventory Searchbar & Color Sets bug

### ISSUE THREAD

**Issue by Moravexios** [133spider/AQLite#85]
2 bugs i found. 

First the Inventory search bar text region overlaps Armour, Helmet, and Cape sections making it impossible to select them. While actually it makes you activate the search bar.

Also with the Colour Sets, the select a colour set bar thats next to "Apply" has dissapeared leaving me unable to open up and select different colour sets.

**Comment by Moravexios** [comment]
Just to add. Im running the Version 16

**Comment by 133spider** [comment]
There was a bug in the loader that caused the components to disappear and freak out
Redownload v7 to fix
Sorry for the inconvenience
